services:
  neo4j_etl:
    image: neo4j_etl:latest
    build:
      context: ./neo4j_etl

  chatbot_api:
    image: chatbot_api:latest
    build:
      context: ./chatbot_api
    ports:
      - "8000:8000"
    restart: on-failure

  chatbot_frontend:
    image: chatbot_frontend:latest
    build:
      context: ./chatbot_frontend
    ports:
      - "8501:8501"
    restart: on-failure
